<a href="https://colab.research.google.com/github/JeanPablo-007/AnaliticaLab/blob/master/Valencia_Alejo_Jean_Pablo_Eval_Tema1_Preprocesamiento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analítica de Datos — Tema 1: Preprocesamiento de datos  
## Notebook evaluativa

**Asignatura:** Analítica de Datos (IAD-2403)  
**Tema:** Preprocesamiento de datos  
**Herramientas permitidas:** NumPy, Pandas  
**Duración sugerida:** 45-50 minutos

### Instrucciones generales
1. Ejecuta en orden.
2. Responde en las celdas marcadas como **Respuesta del estudiante**.
3. No borres evidencias de salida.
4. Guarda tu archivo como: `Apellido_Nombre_Eval_Tema1_Preprocesamiento.ipynb`

## Rúbrica (100 puntos)
- **A. Importación e inspección inicial** (15)
- **B. Detección de errores de calidad** (20)
- **C. Limpieza y tratamiento** (25)
- **D. Filtración y transformación** (20)
- **E. Fusión (`merge`) y resumen final** (15)
- **F. Presentación y claridad** (5)

## 0) Preparación del entorno (no modificar)

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 140)

print("Entorno listo ✅")
print("Pandas:", pd.__version__)
print("NumPy :", np.__version__)

Entorno listo ✅
Pandas: 2.2.2
NumPy : 2.0.2

## 1) Generación del dataset de evaluación (no modificar)

Se crearán:
- `evaluacion_datos/estudiantes_crudo_eval.csv`
- `evaluacion_datos/apoyos_eval.csv`

In [2]:
Path("evaluacion_datos").mkdir(exist_ok=True)

df_crudo_eval = pd.DataFrame({
    "id_estudiante": [201,202,203,204,205,206,207,208,209,210,211,211],
    "nombre": ["Laura","Iván","María","Diego","Sofía","Raúl","Carmen","Joel","Paola","Andrés","Karla","Karla"],
    "edad": [19, 20, np.nan, 22, 21, 19, 20, 23, 21, 20, 22, 22],
    "campus": ["SLP Centro", "slp centro ", "SLP Norte", "SLP Cntro", "Matehuala", "SLP Norte", "Matehuala", "SLP Centro", "SLP Norte", "SLP Centro", "SLP centro", "SLP centro"],
    "modalidad": ["Escolarizada", "escolar", "Mixta", "MIXTA ", "Escolarizada", "Mixta", "Mixta", "Escolarizada", "Escolarizada", "Escolarizada", "Mixta", "Mixta"],
    "promedio": [87, 92, 75, np.nan, 83, 104, 68, 71, 95, 79, 88, 88],
    "asistencia_pct": [93, 86, 80, 88, np.nan, 91, 74, 77, 98, 102, 85, 85],
    "creditos_inscritos": [30, 32, 28, 30, 26, 30, 24, 30, 32, 28, 30, 30],
    "creditos_aprobados": [29, 31, 27, 29, 25, 33, 22, 28, 31, 28, 30, 30]
})

df_apoyos_eval = pd.DataFrame({
    "id_estudiante": [201,203,204,206,208,209,212],
    "beca": ["Sí","No","Sí","No","Sí","No","Sí"],
    "tutoria_horas_mes": [3, 0, 2, 1, 4, 0, 2]
})

df_crudo_eval.to_csv("evaluacion_datos/estudiantes_crudo_eval.csv", index=False)
df_apoyos_eval.to_csv("evaluacion_datos/apoyos_eval.csv", index=False)

print("Archivos creados ✅")
display(df_crudo_eval.head())

Archivos creados ✅

   id_estudiante nombre  edad       campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0   SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro        escolar      92.0            86.0                  32                  31
2            203  María   NaN    SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0    SLP Cntro        MIXTA        NaN            88.0                  30                  29
4            205  Sofía  21.0    Matehuala  Escolarizada      83.0             NaN                  26                  25

# Actividad A. Importación e inspección inicial (15 puntos)

**Instrucciones**
1. Importa ambos CSV en `df` y `apoyos`.
2. Muestra: `shape`, `head()`, `info()`, `describe()`.
3. Escribe una respuesta breve:
   - identificador
   - columnas categóricas

In [3]:
# --- Respuesta del estudiante (A1) ---
# Importa los archivos aquí
df_crudo_eval = pd.read_csv("evaluacion_datos/estudiantes_crudo_eval.csv")
apoyos = pd.read_csv("evaluacion_datos/apoyos_eval.csv")

In [4]:
# --- Respuesta del estudiante (A2) ---
# Muestra shape, head, info y describe
df_crudo_eval.head()
df_crudo_eval.info()
df_crudo_eval.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_estudiante       12 non-null     int64
 1   nombre              12 non-null     object
 2   edad                11 non-null     float64
 3   campus              12 non-null     object
 4   modalidad           12 non-null     object
 5   promedio            11 non-null     float64
 6   asistencia_pct      11 non-null     float64
 7   creditos_inscritos  12 non-null     int64
 8   creditos_aprobados  12 non-null     int64
dtypes: float64(3), int64(3), object(3)
memory usage: 996.0+ bytes

       id_estudiante       edad    promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
count      12.000000  11.000000   11.000000       11.000000           12.000000           12.000000
mean      206.416667  20.818182   84.545455       87.181818           29.166667           28.583333
std         3.476109   1.328020   10.745824        8.518429            2.329000            2.937480
min       201.000000  19.000000   68.000000       74.000000           24.000000           22.000000
25%       203.750000  20.000000   77.000000       82.500000           28.000000           27.750000
50%       206.500000  21.000000   87.000000       86.000000           30.000000           29.000000
75%       209.250000  22.000000   90.000000       92.000000           30.000000           30.250000
max       211.000000  23.000000  104.000000      102.000000           32.000000           33.000000

### Respuesta breve del estudiante (A3)
- Identificador: Id_estudiante
- Columnas categóricas: nombre, campus, modalidad

# Actividad B. Detección de errores de calidad (20 puntos)

Detecta en `df`:
1. Faltantes por columna
2. Duplicados por `id_estudiante`
3. Valores únicos de `campus` y `modalidad`
4. Fuera de rango (`promedio`, `asistencia_pct`)
5. Error lógico (`creditos_aprobados > creditos_inscritos`)

In [5]:
from os import dup
# --- Respuesta del estudiante (B1) ---
# Valores faltantes por columna
df_crudo_eval.isna().sum()

id_estudiante         0
nombre                0
edad                  1
campus                0
modalidad             0
promedio              1
asistencia_pct        1
creditos_inscritos    0
creditos_aprobados    0
dtype: int64

In [6]:
# --- Respuesta del estudiante (B2) ---
# Duplicados por id_estudiante
duplicados_mask = df_crudo_eval.duplicated(subset='id_estudiante', keep=False)
print("Número de filas duplicadas por id_estudiante:", duplicados_mask.sum())
display(df_crudo_eval[duplicados_mask].sort_values("id_estudiante"))

Número de filas duplicadas por id_estudiante: 2

    id_estudiante nombre  edad      campus modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
10            211  Karla  22.0  SLP centro     Mixta      88.0            85.0                  30                  30
11            211  Karla  22.0  SLP centro     Mixta      88.0            85.0                  30                  30

In [7]:
# --- Respuesta del estudiante (B3) ---
# Valores únicos de campus y modalidad
campus = df_crudo_eval['campus'].unique()
print(f"Valores únicos de campus: {campus}")
modalidad = df_crudo_eval['modalidad'].unique()
print(f"Valores únicos de modalidad: {modalidad}")

Valores únicos de campus: ['SLP Centro' 'slp centro ' 'SLP Norte' 'SLP Cntro' 'Matehuala'
 'SLP centro']
Valores únicos de modalidad: ['Escolarizada' 'escolar' 'Mixta' 'MIXTA ']

In [8]:
# --- Respuesta del estudiante (B4) ---
# Fuera de rango: promedio y asistencia_pct
promedio = df_crudo_eval[~df_crudo_eval["promedio"].between(0, 100, inclusive="both") & df_crudo_eval["promedio"].notna()]
asistencia = df_crudo_eval[~df_crudo_eval["asistencia_pct"].between(0, 100, inclusive="both") & df_crudo_eval["asistencia_pct"].notna()]

print("Fuera de rango: promedio\n")
display(promedio[["id_estudiante", "nombre", "promedio"]])

print("\nFuera de rango: asistencia_pct")
display(asistencia[["id_estudiante", "nombre", "asistencia_pct"]])

Fuera de rango: promedio

   id_estudiante nombre  promedio
5            206   Raúl     104.0

Fuera de rango: asistencia_pct

   id_estudiante  nombre  asistencia_pct
9            210  Andrés           102.0

In [9]:
# --- Respuesta del estudiante (B5) ---
# Error lógico en créditos
error_logico = df_crudo_eval[df_crudo_eval["creditos_aprobados"] > df_crudo_eval["creditos_inscritos"]]
error_logico

   id_estudiante nombre  edad     campus modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
5            206   Raúl  19.0  SLP Norte     Mixta     104.0            91.0                  30                  33

### Respuesta breve del estudiante (B6)
Menciona al menos 3 problemas que encontraste:

*   Datos nulos
*   Datos fuera de rango
*   Los datos de los campos "modalidad" estaban mal ingresados

# Actividad C. Limpieza y tratamiento de errores (25 puntos)

Crea `df_limpio` y realiza:
1. Limpieza de texto (`campus`, `modalidad`)
2. Normalización de etiquetas (ej. `slp centro`, `SLP Cntro`, `escolar`, `MIXTA`)
3. Eliminar duplicados por `id_estudiante`
4. Corregir rangos en `promedio` y `asistencia_pct` (0–100)
5. Corregir `creditos_aprobados <= creditos_inscritos`
6. Imputar faltantes (`edad`, `promedio`, `asistencia_pct`) con mediana

In [10]:
df_limpio = df_crudo_eval.copy()

# 9.1 Quitar espacios
df_limpio["campus"] = df_limpio["campus"].astype(str).str.strip()
df_limpio["modalidad"] = df_limpio["modalidad"].astype(str).str.strip()

# 9.2 Normalizar y corregir etiquetas
df_limpio["campus"] = df_limpio["campus"].str.lower().map({
    "slp centro": "SLP Centro",
    "slp cntro": "SLP Centro",
    "slp norte": "SLP Norte",
    "matehuala": "Matehuala"
}).fillna(df_limpio["campus"])

df_limpio["modalidad"] = df_limpio["modalidad"].str.lower().map({
    "escolarizada": "Escolarizada",
    "escolar": "Escolarizada",
    "mixta": "Mixta"
}).fillna(df_limpio["modalidad"])

# 9.3 Eliminar duplicados por id
df_limpio = df_limpio.drop_duplicates(subset=["id_estudiante"], keep="first").copy()

# 9.4 Corregir rangos
df_limpio["promedio"] = df_limpio["promedio"].clip(0, 100)
df_limpio["asistencia_pct"] = df_limpio["asistencia_pct"].clip(0, 100)

# 9.5 Corregir error lógico
df_limpio["creditos_aprobados"] = np.minimum(df_limpio["creditos_aprobados"], df_limpio["creditos_inscritos"])

# 9.6 Imputación simple con mediana
for col in ["edad", "promedio", "asistencia_pct"]:
    df_limpio[col] = df_limpio[col].fillna(df_limpio[col].median())

print("Limpieza completada ✅")
display(df_limpio)

Limpieza completada ✅

    id_estudiante  nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0             201   Laura  19.0  SLP Centro  Escolarizada      87.0            93.0                  30                  29
1             202    Iván  20.0  SLP Centro  Escolarizada      92.0            86.0                  32                  31
2             203   María  20.5   SLP Norte         Mixta      75.0            80.0                  28                  27
3             204   Diego  22.0  SLP Centro         Mixta      85.0            88.0                  30                  29
4             205   Sofía  21.0   Matehuala  Escolarizada      83.0            87.0                  26                  25
5             206    Raúl  19.0   SLP Norte         Mixta     100.0            91.0                  30                  30
6             207  Carmen  20.0   Matehuala         Mixta      68.0            74.0                  24                  22
7             208    Joel  23.0  SLP Centro  Escolarizada      71.0            77.0                  30                  28
8             209   Paola  21.0   SLP Norte  Escolarizada      95.0            98.0                  32                  31
9             210  Andrés  20.0  SLP Centro  Escolarizada      79.0           100.0                  28                  28
10            211   Karla  22.0  SLP Centro         Mixta      88.0            85.0                  30                  30

In [11]:
# --- Respuesta del estudiante (C2) ---
# Mostrar df_limpio.head()
df_limpio.head()

   id_estudiante nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0  SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  SLP Centro  Escolarizada      92.0            86.0                  32                  31
2            203  María  20.5   SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0  SLP Centro         Mixta      85.0            88.0                  30                  29
4            205  Sofía  21.0   Matehuala  Escolarizada      83.0            87.0                  26                  25

In [12]:
# --- Respuesta del estudiante (C3) ---
# Verificación posterior de calidad de datos
verificacion = pd.DataFrame({
    "criterio": [
        "faltantes_totales",
        "duplicados_por_id",
        "campus_invalidos",
        "modalidad_invalidos",
        "promedio_fuera_rango",
        "asistencia_fuera_rango",
        "error_logico_creditos"
    ],
    "valor": [
        int(df_limpio.isna().sum().sum()),
        int(df_limpio.duplicated(subset=["id_estudiante"]).sum()),
        int((~df_limpio["campus"].isin(["SLP Centro", "SLP Norte", "Matehuala"])).sum()),
        int((~df_limpio["modalidad"].isin(["Escolarizada", "Mixta"])).sum()),
        int((~df_limpio["promedio"].between(0, 100, inclusive="both")).sum()),
        int((~df_limpio["asistencia_pct"].between(0, 100, inclusive="both")).sum()),
        int((df_limpio["creditos_aprobados"] > df_limpio["creditos_inscritos"]).sum()),
    ]
})
verificacion

                 criterio  valor
0       faltantes_totales      0
1       duplicados_por_id      0
2        campus_invalidos      0
3     modalidad_invalidos      0
4    promedio_fuera_rango      0
5  asistencia_fuera_rango      0
6   error_logico_creditos      0

### Respuesta breve del estudiante (C4)
¿Por qué conviene limpiar sobre una copia (`df_limpio`) y no sobre `df`? Así evitamos reemplazar los datos del original, para que en el caso de modificar mal los datos, todo el df se arruine

# Actividad D. Filtración y transformación (20 puntos)

Con `df_limpio`:
1. Filtra `promedio < 80`
2. Filtra `campus == 'SLP Centro'` y `modalidad == 'Escolarizada'`
3. Crea `tasa_aprobacion = creditos_aprobados / creditos_inscritos`
4. Crea `riesgo_academico`:
   - Alto: `promedio < 70` o `asistencia_pct < 75`
   - Medio: `promedio < 80`
   - Bajo: otro caso
5. (Opcional) One-hot encoding de `modalidad`

In [40]:
# --- Respuesta del estudiante (D1) ---
# Filtros solicitados
print("Alumnos < 80: \n")
df_limpio_prom = df_limpio[df_limpio["promedio"] < 80]
display(df_limpio_prom)

print("\nAlumnos SLP Centro y Escolarizada: \n")
df_campus = df_limpio[(df_limpio['campus'] == 'SLP Centro') & (df_limpio['modalidad'] == 'Escolarizada')]
display(df_campus)

Alumnos < 80:

,id_estudiante,nombre,edad,campus,modalidad,promedio,asistencia_pct,creditos_inscritos,creditos_aprobados,tasa_aprobacion,riesgo_academico
2,203,María,20.5,SLP Norte,Mixta,75.0,80.0,28,27,0.964286,Medio
6,207,Carmen,20.0,Matehuala,Mixta,68.0,74.0,24,22,0.916667,Alto
7,208,Joel,23.0,SLP Centro,Escolarizada,71.0,77.0,30,28,0.933333,Medio
9,210,Andrés,20.0,SLP Centro,Escolarizada,79.0,100.0,28,28,1.000000,Medio

Alumnos SLP Centro y Escolarizada:

,id_estudiante,nombre,edad,campus,modalidad,promedio,asistencia_pct,creditos_inscritos,creditos_aprobados,tasa_aprobacion,riesgo_academico
0,201,Laura,19.0,SLP Centro,Escolarizada,87.0,93.0,30,29,0.966667,Bajo
1,202,Iván,20.0,SLP Centro,Escolarizada,92.0,86.0,32,31,0.968750,Bajo
7,208,Joel,23.0,SLP Centro,Escolarizada,71.0,77.0,30,28,0.933333,Medio
9,210,Andrés,20.0,SLP Centro,Escolarizada,79.0,100.0,28,28,1.000000,Medio

In [28]:
# --- Respuesta del estudiante (D2) ---
# Crear tasa_aprobacion y riesgo_academico
df_limpio_aprobados = df_limpio[df_limpio['promedio'] > 80][["id_estudiante", "nombre", "promedio"]]

df_limpio["tasa_aprobacion"] = df_limpio["creditos_aprobados"] / df_limpio["creditos_inscritos"]

condiciones = [
    (df_limpio["promedio"] < 70) | (df_limpio["asistencia_pct"] < 75),
    (df_limpio["promedio"] < 80)
]
opciones = ["Alto", "Medio"]
df_limpio["riesgo_academico"] = np.select(condiciones, opciones, default="Bajo")

In [29]:
# --- Respuesta del estudiante (D3) ---
# Mostrar evidencia de transformación
print("Taza de aprobación: \n")
display(df_limpio_aprobados)

display(df_limpio[["id_estudiante", "promedio", "asistencia_pct", "tasa_aprobacion", "riesgo_academico"]])

print("\nDistribución de riesgo:")
display(df_limpio["riesgo_academico"].value_counts())

print("\nPromedio por campus:")
display(df_limpio.groupby("campus")["promedio"].mean().round(2))

Taza de aprobación:

    id_estudiante nombre  promedio
0             201  Laura      87.0
1             202   Iván      92.0
3             204  Diego      85.0
4             205  Sofía      83.0
5             206   Raúl     100.0
8             209  Paola      95.0
10            211  Karla      88.0

    id_estudiante  promedio  asistencia_pct  tasa_aprobacion riesgo_academico
0             201      87.0            93.0         0.966667             Bajo
1             202      92.0            86.0         0.968750             Bajo
2             203      75.0            80.0         0.964286            Medio
3             204      85.0            88.0         0.966667             Bajo
4             205      83.0            87.0         0.961538             Bajo
5             206     100.0            91.0         1.000000             Bajo
6             207      68.0            74.0         0.916667             Alto
7             208      71.0            77.0         0.933333            Medio
8             209      95.0            98.0         0.968750             Bajo
9             210      79.0           100.0         1.000000            Medio
10            211      88.0            85.0         1.000000             Bajo

Distribución de riesgo:

riesgo_academico
Bajo     7
Medio    3
Alto     1
Name: count, dtype: int64

Promedio por campus:

campus
Matehuala     75.50
SLP Centro    83.67
SLP Norte     90.00
Name: promedio, dtype: float64

### Respuesta breve del estudiante (D4)
¿Cuál es la diferencia entre **filtrar** y **transformar** datos?
* cuando se filtran los datos solo se seleccionan
* cuando se transforman los datos se modifican esos datos

# Actividad E. Fusión (`merge`) y resumen final (15 puntos)

1. Une `df_limpio` con `apoyos` por `id_estudiante` con `how='left'` e `indicator=True`
2. Guarda en `df_final`
3. Muestra `shape` y conteo de `_merge`
4. Resume:
   - promedio general
   - promedio por `campus`
   - distribución de `riesgo_academico`
5. Guarda CSV en `salida_eval/estudiantes_preprocesados_eval.csv`

In [36]:
# --- Respuesta del estudiante (E1) ---
# Merge y creación de df_final
df_final = pd.merge(df_limpio, apoyos, on="id_estudiante", how="left", indicator=True)
df_final

,id_estudiante,nombre,edad,campus,modalidad,promedio,asistencia_pct,creditos_inscritos,creditos_aprobados,tasa_aprobacion,riesgo_academico,beca,tutoria_horas_mes,_merge
0,201,Laura,19.0,SLP Centro,Escolarizada,87.0,93.0,30,29,0.966667,Bajo,Sí,3.0,both
1,202,Iván,20.0,SLP Centro,Escolarizada,92.0,86.0,32,31,0.968750,Bajo,NaN,NaN,left_only
2,203,María,20.5,SLP Norte,Mixta,75.0,80.0,28,27,0.964286,Medio,No,0.0,both
3,204,Diego,22.0,SLP Centro,Mixta,85.0,88.0,30,29,0.966667,Bajo,Sí,2.0,both
4,205,Sofía,21.0,Matehuala,Escolarizada,83.0,87.0,26,25,0.961538,Bajo,NaN,NaN,left_only
5,206,Raúl,19.0,SLP Norte,Mixta,100.0,91.0,30,30,1.000000,Bajo,No,1.0,both
6,207,Carmen,20.0,Matehuala,Mixta,68.0,74.0,24,22,0.916667,Alto,NaN,NaN,left_only
7,208,Joel,23.0,SLP Centro,Escolarizada,71.0,77.0,30,28,0.933333,Medio,Sí,4.0,both
8,209,Paola,21.0,SLP Norte,Escolarizada,95.0,98.0,32,31,0.968750,Bajo,No,0.0,both
9,210,Andrés,20.0,SLP Centro,Escolarizada,79.0,100.0,28,28,1.000000,Medio,NaN,NaN,left_only
10,211,Karla,22.0,SLP Centro,Mixta,88.0,85.0,30,30,1.000000,Bajo,NaN,NaN,left_only

In [24]:
# --- Respuesta del estudiante (E2) ---
print("Promedio general:", round(df_final["promedio"].mean(), 2))
print("Asistencia promedio:", round(df_final["asistencia_pct"].mean(), 2))

# Resumen final

Promedio general: 83.91
Asistencia promedio: 87.18

In [41]:
# --- Respuesta del estudiante (E3) ---
# Guardar archivo final en CSV
Path("salida_eval").mkdir(exist_ok=True)
df_final.to_csv("salida_eval/estudiantes_preprocesados_eval.csv", index=False)

# Actividad F. Reflexión final (5 puntos)

Responde brevemente:
1. ¿Qué error fue más frecuente?
 Confundía el uso del punto por la coma
2. ¿Qué corrección fue más importante para evitar errores de análisis?
 Saber el funcionamiento de los métodos y así saber que usar
3. ¿Qué pasaría si este dataset se usa sin limpiar?
 Los datos serían de mala calidad y al momento de usarse no servirían de nada

## Lista de cotejo antes de entregar
- [ ] Corrí todas las celdas en orden
- [ ] Mi código no produce errores
- [ ] Mostré evidencia de cada actividad
- [ ] Creé `df_limpio` y `df_final`
- [ ] Guardé el CSV final
- [ ] Respondí las preguntas breves

## Apéndice (recordatorio rápido de funciones útiles)
`read_csv`, `shape`, `head`, `info`, `describe`, `isna`, `duplicated`, `drop_duplicates`,
`str.strip`, `str.lower`, `map`, `clip`, `fillna`, `np.minimum`, filtros booleanos, `np.select`,
`get_dummies`, `merge`, `to_csv`

## Observaciones del docente (uso exclusivo del profesor)
- Puntuación:
- Fortalezas:
- Áreas de mejora:
- Recomendación: